### PR TITLE
Enabled logging.

### LINKED ISSUE #38: Enable logging
### Problem Description
Implementing logging in our program. Using either built in logging tools with java.util.logging, or using a logging framework like Log4j

### PR DESCRIPTION
**Pull request by BarbieQkiller**
### Related Issue(s)
Closes #38 

### Proposed Changes
 This PR replaces system.out.println with java util logging.

### Description
Replaced system.out.println and e.printStackTrace with java util logging and added test.

### Checklist
- [ x] Code compiles correctly
- [x ] Extended the README / documentation, if necessary
- [ x] Added tests to cover new changes
- [ x] All new and existing tests passed
- [ x] The code follows the code style of this project

----

| <a href="https://ellipsis.dev" target="_blank">Ellipsis</a> | :rocket: This PR description was created by [Ellipsis](https://www.ellipsis.dev) for commit da94f53ef53f618f50ce5acfd0dedd919b74498f.  | 
|--------|--------|

### Summary:
This PR enhances the logging mechanism by replacing `System.out.println` and `e.printStackTrace` with `java.util.logging`, and adds relevant tests.

**Key points**:
- Replaced `System.out.println` and `e.printStackTrace` with `java.util.logging` in `ClientHandler`, `Main`, `PackageReader`, and `Server` classes.
- Added a test to ensure logging is working as expected.
- Added a new `SpyLogHandler` class for testing purposes.

----
Generated with :heart: by [ellipsis.dev](https://www.ellipsis.dev)

### CODE REVIEW

**Review by nilssonjn — COMMENTED** [review]
Looks good. Nice with javas logger instead of using a dependency. However there seems to be errors in CI pipeline. If we run this command: 

> mvn -X clean verify sonar:sonar

it gives this message:

Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator

**Comment by marcusju23** [comment]
The code looks solid. I'm curious, could there be any challenges or considerations we need to be aware of when forking the project and running the pipeline? Wondering if that might be the reason for the failed checks? 🤔

**Review by aeldin — COMMENTED** [review]
This looks good. To fix the checks you need to push your branch directly to the project instead of using a fork.

**Review by Rishad11 — DISMISSED** [review]
Looks good to me. Well done on incorporating structured logging throughout the application.

**Comment by LMMAndreasson** [comment]
This cannot be merged due to being behind the main branch. This can be fixed by rebasing. See pull #66

**Comment by LMMAndreasson** [comment]
There are further issues regarding this being a fork rather than a branch. This causes issues with SonarCloud. Closing,

**Pull request closed without merging**
