### PR TITLE
add README.md

### PR DESCRIPTION
**Pull request by ByHatice**
---
name: Add README.md
about: Describing the project and its aim

---

### Proposed Changes

- **Change 1**: [Description] - Creating README.md.
- **Change 2**: [Description] - Describing the project and its aim.

Here are some example changes:
- Created README.
- Added description of MQTT and Shelly.
- Described the aim for this project.

### CODE REVIEW

**Review by Ebyrdeu — CHANGES_REQUESTED** [review]
While it's not much in text, your text is not formatted in any way, which makes it harder to distinguish from each other. There is [documentation](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) on how you can format text in an MD file. Additionally, IntelliJ supports this, so you can easily look at and edit it at the same time.
Screenshot 2024-02-02 135212

**Comment by ByHatice** [comment]
Thanks for the feedback. I have now updated README.md ae7ac0d
Requires further modification in the future.

**Review by Ebyrdeu — DISMISSED** [review]
Looks good. Not sure why you have 15 empty rows at the begning at file, but it doesn't matter that much, so don't worry about it.

**Review by Win-ther — APPROVED** [review]

**Review by yrlacornelia — APPROVED** [review]
Looks good!

**Pull request merged**
