### PR TITLE
18 handling disconnect

### LINKED ISSUE #18: Handling disconnect
### Problem Description
The DISCONNECT Packet is the final Control Packet sent from the Client to the Server. It indicates that the Client is disconnecting cleanly.

[Documentation](https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718090)

### PR DESCRIPTION
**Pull request by Win-ther**
### Related Issue(s)
Closes #18

### Proposed Changes
- Add detection for disconnect package PackageReader
- Add methodcall and closing+removal of connection when DISCONNECT package is sent from Client.
- Add tests for disconnect

### Description
Add a way to detect DISCONNECT packages sent from Client. When this is detected, the Socket will be closed and the connection will be removed from the broker. You can now disconnect and reconnect to the broker.

### CODE REVIEW

**Comment by Win-ther** [comment]
When #33 is merged into main, there will be conflicts that needs to be resolved and I will look at why Thunder CI pipeline fails then.

**Comment by vonfredd** [comment]
> ### Related Issue(s)
> Closes #18
> 
> ### Proposed Changes
> * Add detection for disconnect package PackageReader
> * Add methodcall and closing+removal of connection when DISCONNECT package is sent from Client.
> * Add tests for disconnect
> 
> ### Description
> Add a way to detect DISCONNECT packages sent from Client. When this is detected, the Socket will be closed and the connection will be removed from the broker. **You can now disconnect and reconnect to the broker**.

It seems like I missing something. I am not able to disconnect and reconnect and cannot find the block of code for the action. Am I blind? 😮 Otherwise I think the code and tests looks good.

**Comment by Win-ther** [comment]
> It seems like I am missing something. I am not able to disconnect and reconnect and cannot find the block of code for the action. Am I blind? 😮 Otherwise I think the code and tests looks good.

Are you on the correct branch and on the correct commit? Because I can find the code and it works for me. 
Can you see the code in the 'Files changed' - tab in the PR?

**Comment by vonfredd** [comment]
> Are you on the correct branch and on the correct commit? Because I can find the code and it works for me. Can you see the code in the 'Files changed' - tab in the PR?

Yes, I am on correct branch and latest commit 1d5d36d. I do not se any reconnect block in 'Files changed'. I was able to connect with the MQTT program Martin showed us, but after disconnecting I wasnt able to reconnect. Is there a test or something that I am missing?

**Comment by Win-ther** [comment]
> 
> Yes, I am on correct branch and latest commit [1d5d36d](https://github.com/fungover/thunder/commit/1d5d36dffa3e0211994239d59612954555d88297). I do not se any reconnect block in 'Files changed'. I was able to connect with the MQTT program Martin showed us, but after disconnecting I wasnt able to reconnect. Is there a test or something that I am missing?

Oh there is no reconnect block of code, the client will only send a CONNECT packet to connect and a DISCONNECT packet to disconnect. There is no RECONNECT packet that the client will send.
To reconnect you just need to press the connect button again after disconnecting. It works fine for me both in MQTTX and in the App IOT MQTT Panel. 
I'm not sure why it's not working for you.

image

**Comment by vonfredd** [comment]
> Oh there is no reconnect block of code, the client will only send a CONNECT packet to connect and a DISCONNECT packet to disconnect. There is no RECONNECT packet that the client will send. To reconnect you just need to press the connect button again after disconnecting. It works fine for me both in MQTTX and in the App IOT MQTT Panel. I'm not sure why it's not working for you.
> 

You are right. I probably messed something up yesterday because now it works for me 😴. I do not know why I was looking for a reconnect block since the client only need to be accepted by the socket and send a new connect package at validation😄 
Code looks good!

**Review by vonfredd — APPROVED** [review]

**Review by TrungMa1 — APPROVED** [review]

**Pull request merged**
