### PR TITLE
25 feature subscribe to topic

### LINKED ISSUE #25: [FEATURE] - Subscribe to topic
### Problem Description
A connected client can subscribe to a topic with a SUBSCRIBE message. 
buffer[0] == (byte) 0x82
https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718063

After storing any needed information as what topic we subscribe to we send a SUBACK
https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718068

### PR DESCRIPTION
**Pull request by vonfredd**
### Related Issue
Closes #25

### Proposed Changes
A subscription class that handles the subscriptions of the apps clients. A client should be able to subscribe to a specific topic or to multiple topics at once with the help of wildcards in the topic name. Update ClientHandler to be able to listen for different types of packets.

### Description
- **Change 1**: Added subscription class to handle subscriptions.
- **Change 2**: A client can subscribe to multiple topics.
- **Change 3**: A client can subscribe to topics based on wildcards. Will subscribe to all topics that matches wildcard.
- **Change 4**: Edited clientHandler loop to be able to read until disconnected.
- **Change 5**: readFromClient() now checks if disconnect packet is sent from client and then calls for isCleanDisconnect().
- **Change 6**: Added tests for subscriptions

----

| <a href="https://ellipsis.dev" target="_blank">Ellipsis</a> | :rocket: This PR description was created by [Ellipsis](https://www.ellipsis.dev) for commit 7ce881511e9b24d575af627fa03075394ed35c33.  | 
|--------|--------|

### Summary:
This PR introduces a new `Subscription` class, updates packet handling in `ClientHandler`, modifies `PackageReader` for disconnect packet checking, and includes relevant tests, allowing clients to subscribe to multiple topics and to topics based on wildcards.

**Key points**:
- Introduced a new `Subscription` class to manage client subscriptions to topics.
- Updated `read` method in `Subscription` class to handle different types of packets.
- Refactored `listOfMatchedTopics` method in `Subscription` class to use Java 8 streams.
- Updated `ClientHandler` class to listen for different types of packets and handle client disconnections.
- Added tests for the new functionality.
- A client can subscribe to multiple topics and to topics based on wildcards.

----
Generated with :heart: by [ellipsis.dev](https://www.ellipsis.dev)

### CODE REVIEW

**Comment by kappsegla** [comment]
Since we are using a multi threaded implementation of our application we can't have different threads to update the subscription HashMap directly in Subscription class.

We have two options to solve this problem:

1. Replace HashMap with a ConcurrentHashMap. https://www.baeldung.com/java-concurrent-map
2. Make sure only one thread at a time can access the map using locks. https://www.baeldung.com/java-concurrent-locks

As a value the HashMap uses an arraylist so the same problem happens with that.
Even if we use the first alternative we must make sure to do read and updates atomic so might be best to use a lock to make sure all the necessary changes are done one thread at a time?

**Review by kappsegla — CHANGES_REQUESTED** [review]
Since our application is multi threaded we need to use locks when reading and changing any shared resource like HashMap that stores topics.

**Comment by vonfredd** [comment]
> Since our application is multi threaded we need to use locks when reading and changing any shared resource like HashMap that stores topics.

Maby we won't even need a lock? It seems like the ConcurrentHashMap [locks the part that is being modified automatically](https://www.baeldung.com/java-concurrent-map#:~:text=Each%20bucket%20can%20be%20independently%20locked%20by%20locking%20the%20very%20first%20node%20in%20the%20bucket.%20Read%20operations%20do%20not%20block%2C%20and%20update%20contentions%20are%20minimized.). Also mentioned [here](https://www.baeldung.com/concurrenthashmap-reading-and-writing#:~:text=On%20the%20other,and%20synchronizedMap%20collections.). So I think the map could be ConcurrentHashMap and we could use putIfAbsent() to put new values to the map. 
Or am I missing something vital to why we would want to use a Lock object and not just the "built in lock"?

**Comment by kappsegla** [comment]
> > Since our application is multi threaded we need to use locks when reading and changing any shared resource like HashMap that stores topics.
> 
> Maby we do not even need a lock? It seems like the ConcurrentHashMap [locks the part that is being modified automatically](https://www.baeldung.com/java-concurrent-map#:~:text=Each%20bucket%20can%20be%20independently%20locked%20by%20locking%20the%20very%20first%20node%20in%20the%20bucket.%20Read%20operations%20do%20not%20block%2C%20and%20update%20contentions%20are%20minimized.). Also mentioned [here](https://www.baeldung.com/concurrenthashmap-reading-and-writing#:~:text=On%20the%20other,and%20synchronizedMap%20collections.). So I think the map could be ConcurrentHashMap and we could use putIfAbsent() to put new values to the map. Or am I missing something vital to why we would want to use a Lock object and not just the "built in lock"?

If we have a map with single objects as values for example Map<String,String> that approach should work. But now we have a Map<Topic, List<Socket>> so an update of this have multiple steps.

1. Search the map for a list belonging to a specific Topic.
2. Update the list with add or remove

All these operations must be thread safe and done by one thread at a time so two threads aren't trying to do these updates simultaneously. So even if we use a ConcurrentHashMap we might also need to use a thread safe List implementation, CopyOnWriteArrayList is a good alternative here for us since we probably will do more reads than writes.

**Review by kappsegla — APPROVED** [review]

**Pull request merged**
